@startuml
left to right direction
skinparam packageStyle rectangle
actor Player


rectangle BLACKJACK! {
Player --(PLAY)

(PLAY)--(Dealer Gives 2 Cards)

(Dealer Gives 2 Cards) -- [HIT]
(Dealer Gives 2 Cards) -- [STAND]


[HIT] -- [Greater Than 21]
[HIT] -- (Less Than 21)
[STAND] -- (Less Than 21)

(Less Than 21) -.> (Higher Than Dealer)
(Less Than 21) -.> (Lower Than Dealer)
(Greater Than 21) -.> (BUSTED!)


actor Player_wins
(Higher Than Dealer) --> Player_wins
(Lower Than Dealer) -- [LOSE]
}






actor Player_lose
[LOSE] --> Player_lose
(BUSTED!) --> [LOSE]




@enduml